version: '3'
services:
  postgres:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  ingestion:
    image: bedrock/ingestion:latest
    volumes:
      - ./ingestion/ingestion:/ingestion
    environment:
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - 8080:8080
    build:
      dockerfile: Dockerfile.ingestion
      context: ./ingestion
    restart: on-failure
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres: